---

- hosts: all
  roles:
    - common
#    - sshd
#    - firewalld

#- hosts: webservers
#  roles:
#    - apache

- hosts: testweb1
  roles:
    - apache
    - webserver1

- hosts: testweb2
  roles:
    - apache
    - webserver2

- hosts: wlb
  roles:
    - haproxy
